### ISSUE TITLE
ERR ante handler panicked error="runtime error: 

### ISSUE THREAD

**Issue by danlix2000** [xpladev/xpla#123]
I am uisng Golang v1.18 and v1.4.0 tag

getting below error when I run xplad start

`5:27PM INF asserted all invariants duration=0.376221 height=0 module=x/crisis
5:27PM ERR ante handler panicked error="runtime error: invalid memory address or nil pointer dereference" stack trace="goroutine 1 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\ngithub.com/xpladev/xpla/ante.Recover({0x3204d00, 0xc000ff9e00}, 0xc0011f9c38)\n\tgithub.com/xpladev/xpla/ante/ante.go:197 +0xff\npanic({0x2087660, 0x433f4d0})\n\truntime/panic.go:838 +0x207\ngithub.com/cosmos/cosmos-sdk/x/auth/ante.SetUpContextDecorator.AnteHandle.func1()\n\tgithub.com/cosmos/cosmos-sdk@v0.45.16/x/auth/ante/setup.go:57 +0x1fa\npanic({0x2087660, 0x433f4d0})\n\truntime/panic.go:838 +0x207\nmath/big.(*Int).Sign(...)\n\tmath/big/int.go:39\ngithub.com/cosmos/cosmos-sdk/types.Dec.IsZero(...)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.16/types/decimal.go:210\ngithub.com/xpladev/xpla/ante.MinGasPriceDecorator.AnteHandle({{_, _, _}, {_, _}, {_, _}}, {{0x3203790, 0xc001110750}, {0x32133c8, ...}, ...}, ...)\n\tgithub.com/xpladev/xpla/ante/fee.go:50 +0x298\ngithub.com/cosmos/cosmos-sdk/types.ChainAnteDecorators.func1({{0x3203790, 0xc001110750}, {0x32133c8, 0xc00059d680}, {{0x0, 0x0}, {0xc00148e4b0, 0xe}, 0x0, {0x0, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.16/types/handler.go:40 +0x158\ngithub.com/cosmos/cosmos-sdk/x/auth/ante.RejectExtensionOptionsDecorator.AnteHandle({}, {{0x3203790, 0xc001110750}, {0x32133c8, 0xc00059d680}, {{0x0, 0x0}, {0xc00148e4b0, 0xe}, 0x0, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.16/x/auth/ante/ext.go:35 +0x12e\ngithub.com/cosmos/cosmos-sdk/types.ChainAnteDecorators.func1({{0x3203790, 0xc001110750}, {0x32133c8, 0xc00059d680}, {{0x0, 0x0}, {0xc00148e4b0, 0xe}, 0x0, {0x0, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.16/types/handler.go:40 +0x158\ngithub.com/CosmWasm/wasmd/x/wasm/keeper.CountTXDecorator.AnteHandle({{_, _}}, {{0x3203720, 0xc000052098}, {0x32133c8, 0xc00059d680}, {{0x0, 0x0}, {0xc00148e4b0, 0xe}, ...}, ...}, ...)\n\tgithub.com/CosmWasm/wasmd@v0.33.0/x/wasm/keeper/ante.go:44 +0x3b3\ngithub.com/cosmos/cosmos-sdk/types.ChainAnteDecorators.func1({{0x3203720, 0xc000052098}, {0x32133c8, 0xc00059d680}, {{0x0, 0x0}, {0xc00148e4b0, 0xe}, 0x0, {0x0, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.16/types/handler.go:40 +0x158\ngithub.com/CosmWasm/wasmd/x/wasm/keeper.LimitSimulationGasDecorator.AnteHandle({_}, {{0x3203720, 0xc000052098}, {0x32133c8, 0xc00059d680}, {{0x0, 0x0}, {0xc00148e4b0, 0xe}, 0x0, ...}, ...}, ...)\n\tgithub.com/CosmWasm/wasmd@v0.33.0/x/wasm/keeper/ante.go:83 +0x744\ngithub.com/cosmos/cosmos-sdk/types.ChainAnteDecorators.func1({{0x3203720, 0xc000052098}, {0x32133c8, 0xc00059d680}, {{0x0, 0x0}, {0xc00148e4b0, 0xe}, 0x0, {0x0, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.16/types/handler.go:40 +0x158\ngithub.com/cosmos/cosmos-sdk/x/auth/ante.SetUpContextDecorator.AnteHandle({}, {{0x3203720, 0xc000052098}, {0x32133c8, 0xc00059d680}, {{0x0, 0x0}, {0xc00148e4b0, 0xe}, 0x0, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.16/x/auth/ante/setup.go:62 +0x66f\ngithub.com/cosmos/cosmos-sdk/types.ChainAnteDecorators.func1({{0x3203720, 0xc000052098}, {0x32133c8, 0xc00059d680}, {{0x0, 0x0}, {0xc00148e4b0, 0xe}, 0x0, {0x0, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.16/types/handler.go:40 +0x158\ngithub.com/xpladev/xpla/ante.RejectDelegateVolunteerValidatorDecorator.AnteHandle({{{_, _}, {_, _}, {_, _}, {_, _}}}, {{0x3203720, 0xc000052098}, ...}, ...)\n\tgithub.com/xpladev/xpla/ante/volunteer.go:48 +0x2ee\ngithub.com/cosmos/cosmos-sdk/types.ChainAnteDecorators.func1({{0x3203720, 0xc000052098}, {0x32133c8, 0xc00059d680}, {{0x0, 0x0}, {0xc00148e4b0, 0xe}, 0x0, {0x0, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.16/types/handler.go:40 +0x158\ngithub.com/xpladev/xpla/ante.AuthzLimiterDecorator.AnteHandle({{_, _, _}}, {{0x3203720, 0xc000052098}, {0x32133c8, 0xc00059d680}, {{0x0, 0x0}, {0xc00148e4b0, ...}, ...}, ...}, ...)\n\tgithub.com/xpladev/xpla/ante/authz.go:47 +0x1ce\ngithub.com/cosmos/cosmos-sdk/types.ChainAnteDecorators.func1({{0x3203720, 0xc000052098}, {0x32133c8, 0xc00059d680}, {{0x0, 0x0}, {0xc00148e4b0, 0xe}, 0x0, {0x0, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.16/types/handler.go:40 +0x158\ngithub.com/evmos/ethermint/app/ante.RejectMessagesDecorator.AnteHandle({}, {{0x3203720, 0xc000052098}, {0x32133c8, 0xc00059d680}, {{0x0, 0x0}, {0xc00148e4b0, 0xe}, 0x0, ...}, ...}, ...)\n\tgithub.com/evmos/ethermint@v0.19.3/app/ante/reject_msgs.go:24 +0x10e\ngithub.com/cosmos/cosmos-sdk/types.ChainAnteDecorators.func1({{0x3203720, 0xc000052098}, {0x32133c8, 0xc00059d680}, {{0x0, 0x0}, {0xc00148e4b0, 0xe}, 0x0, {0x0, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.16/types/handler.go:40 +0x158\ngithub.com/xpladev/xpla/ante.NewAnteHandler.func1({{0x3203720, 0xc000052098}, {0x32133c8, 0xc00059d680}, {{0x0, 0x0}, {0xc00148e4b0, 0xe}, 0x0, {0x0, ...}, ...}, ...}, ...)\n\tgithub.com/xpladev/xpla/ante/ante.go:110 +0x6f6\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx(0xc000165dc0, 0x3, {0xc000123b80, 0x26c, 0x26c})\n\tgithub.com/cosmos/cosmos-sdk@v0.45.16/baseapp/baseapp.go:684 +0x779\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).DeliverTx(0xc000165dc0, {{0xc000123b80?, 0x31f2270?, 0xc0010280f0?}})\n\tgithub.com/cosmos/cosmos-sdk@v0.45.16/baseapp/abci.go:286 +0x205\ngithub.com/cosmos/cosmos-sdk/x/genutil.DeliverGenTxs({{0x3203720, 0xc000052098}, {0x32133c8, 0xc000bac400}, {{0x0, 0x0}, {0xc00148e4b0, 0xe}, 0x0, {0x0, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.16/x/genutil/gentx.go:108 +0x166\ngithub.com/cosmos/cosmos-sdk/x/genutil.InitGenesis(...)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.16/x/genutil/genesis.go:18\ngithub.com/cosmos/cosmos-sdk/x/genutil.AppModule.InitGenesis({{}, {_, _}, {_, _}, _, {_, _}}, {{0x3203720, 0xc000052098}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.16/x/genutil/module.go:98 +0x15e\ngithub.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(_, {{0x3203720, 0xc000052098}, {0x32133c8, 0xc000bac400}, {{0x0, 0x0}, {0xc00148e4b0, 0xe}, 0x0, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.16/types/module/module.go:327 +0x29d\ngithub.com/xpladev/xpla/app.(*XplaApp).InitChainer(_, {{0x3203720, 0xc000052098}, {0x32133c8, 0xc000bac400}, {{0x0, 0x0}, {0xc00148e4b0, 0xe}, 0x0, ...}, ...}, ...)\n\tgithub.com/xpladev/xpla/app/app.go:325 +0x20e\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc000165dc0, {{0x0, 0xeda914f18, 0x0}, {0xc00148e4b0, 0xe}, 0xc000521b00, {0x4612048, 0x0, 0x0}, ...})\n\tgithub.com/cosmos/cosmos-sdk@v0.45.16/baseapp/abci.go:64 +0x455\ngithub.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc001101920, {{0x0, 0xeda914f18, 0x0}, {0xc00148e4b0, 0xe}, 0xc000521b00, {0x4612048, 0x0, 0x0}, ...})\n\tgithub.com/tendermint/tendermint@v0.35.4/abci/client/local_client.go:272 +0x118\ngithub.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0x0?, {{0x0, 0xeda914f18, 0x0}, {0xc00148e4b0, 0xe}, 0xc000521b00, {0x4612048, 0x0, 0x0}, ...})\n\tgithub.com/tendermint/tendermint@v0.35.4/proxy/app_conn.go:77 +0x55\ngithub.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0x2372ad9, 0x7}}, {0xc00148e4b0, 0xe}, 0x1, 0x0, {{0x0, ...}, ...}, ...}, ...)\n\tgithub.com/tendermint/tendermint@v0.35.4/consensus/replay.go:319 +0xd78\ngithub.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc0011ff6a8, {0x3216b18, 0xc000b35c70})\n\tgithub.com/tendermint/tendermint@v0.35.4/consensus/replay.go:268 +0x3c8\ngithub.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0x2372ad9, 0x7}}, {0xc00148e4b0, 0xe}, 0x1, 0x0, ...}, ...)\n\tgithub.com/tendermint/tendermint@v0.35.4/node/node.go:329 +0x1b8\ngithub.com/tendermint/tendermint/node.NewNode(0xc000b92640, {0x31ff740, 0xc0015e46e0}, 0xc00157e3b0, {0x31e4540, 0xc000ff4858}, 0x0?, 0x0?, 0xc00157e520, {0x3204d00, ...}, ...)\n\tgithub.com/tendermint/tendermint@v0.35.4/node/node.go:779 +0x597\ngithub.com/evmos/ethermint/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x321f940, 0xc0012b2b10}, {0x0, 0x0}, {0x3209558, 0xc001328680}, ...}, ...)\n\tgithub.com/evmos/ethermint@v0.19.3/server/start.go:310 +0xcb3\ngithub.com/evmos/ethermint/server.StartCmd.func2(0xc001356f00?, {0x4612048?, 0x0?, 0x0?})\n\tgithub.com/evmos/ethermint@v0.19.3/server/start.go:119 +0x228\ngithub.com/spf13/cobra.(*Command).execute(0xc001356f00, {0x4612048, 0x0, 0x0})\n\tgithub.com/spf13/cobra@v1.6.1/command.go:916 +0x862\ngithub.com/spf13/cobra.(*Command).ExecuteC(0xc000dadb00)\n\tgithub.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bc\ngithub.com/spf13/cobra.(*Command).Execute(...)\n\tgithub.com/spf13/cobra@v1.6.1/command.go:968\ngithub.com/spf13/cobra.(*Command).ExecuteContext(...)\n\tgithub.com/spf13/cobra@v1.6.1/command.go:961\ngithub.com/cosmos/cosmos-sdk/server/cmd.Execute(0x237028d?, {0xc00101b080, 0x12})\n\tgithub.com/cosmos/cosmos-sdk@v0.45.16/server/cmd/execute.go:36 +0x1eb\nmain.main()\n\tgithub.com/xpladev/xpla/cmd/xplad/main.go:26 +0x65\n"
panic: runtime error: invalid memory address or nil pointer dereference: panic
`

**Comment by Dilrong** [comment]
I know using golang v1.1.9 since xpla v1.3.0.

**Comment by Kwaskoff** [comment]
the same error

**Comment by Kwaskoff** [comment]
yep! I tried to launch another network and it had the same error =))
I think I updated server today and it download some new packages with this effect =)) Magic!

**Comment by Kwaskoff** [comment]
this error exists because the new version of the binary cannot work with the old block. Start your node from a snapshot or state-sync and it'll be ok
