### ISSUE TITLE
V1.2.0 panic. 

### ISSUE THREAD

**Issue by gearlbrace** [xpladev/xpla#68]
Deleted app and config.toml. then restarted with v1.2.0. xplad panics with below.
Reverting to v1.1.3 resolves.

```
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]: 11:11PM INF ABCI Handshake App Info hash="սܙ\x02ˉS@\x19f\x04;j\x1fDH�*A�+��Ԭ.˱���" height=2423437 module=consensus protocol-version=0 server=node software-version=v1.2.0
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]: 11:11PM INF ABCI Replay Blocks appHeight=2423437 module=consensus server=node stateHeight=2423437 storeHeight=2423438
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]: 11:11PM INF Replay last block using real app module=consensus server=node
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]: panic: runtime error: invalid memory address or nil pointer dereference
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x5e5f7f]
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]: goroutine 1 [running]:
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]: math/big.(*Int).Mul(0xc0040581a0, 0xc004058180, 0x0)
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]:         math/big/int.go:168 +0x9f
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]: github.com/cosmos/cosmos-sdk/types.Dec.Mul({0x2b98158?}, {0x0?})
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]:         github.com/cosmos/cosmos-sdk@v0.45.9/types/decimal.go:253 +0x3d
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]: github.com/evmos/ethermint/x/feemarket/keeper.(*Keeper).EndBlock(_, {{0x2b8a290, 0xc0001ba140}, {0x2b99e40, 0xc00b710100}, {{0xb, 0x0}, {0xc00d736520, 0xe}, 0x24fa8e, ...}, ...}, ...)
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]:         github.com/evmos/ethermint@v0.19.3/x/feemarket/keeper/abci.go:54 +0x3a9
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]: github.com/evmos/ethermint/x/feemarket.AppModule.EndBlock(...)
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]:         github.com/evmos/ethermint@v0.19.3/x/feemarket/module.go:154
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]: github.com/cosmos/cosmos-sdk/types/module.(*Manager).EndBlock(_, {{0x2b8a290, 0xc0001ba140}, {0x2b99e40, 0xc00b710100}, {{0xb, 0x0}, {0xc00d736520, 0xe}, 0x24fa8e, ...}, ...}, ...)
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]:         github.com/cosmos/cosmos-sdk@v0.45.9/types/module/module.go:512 +0x4c2
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]: github.com/xpladev/xpla/app.(*XplaApp).EndBlocker(_, {{0x2b8a290, 0xc0001ba140}, {0x2b99e40, 0xc00b710100}, {{0xb, 0x0}, {0xc00d736520, 0xe}, 0x24fa8e, ...}, ...}, ...)
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]:         github.com/xpladev/xpla/app/app.go:799 +0x98
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]: github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).EndBlock(0xc0001dba40, {0x20?})
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]:         github.com/cosmos/cosmos-sdk@v0.45.9/baseapp/abci.go:202 +0x1fe
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]: github.com/tendermint/tendermint/abci/client.(*localClient).EndBlockSync(0xc000597080, {0xc000597080?})
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]:         github.com/tendermint/tendermint@v0.34.21/abci/client/local_client.go:288 +0xdf
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]: github.com/tendermint/tendermint/proxy.(*appConnConsensus).EndBlockSync(0xc00d779620?, {0x20?})
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]:         github.com/tendermint/tendermint@v0.34.21/proxy/app_conn.go:89 +0x24
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]: github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x2b8b7c8?, 0xc00d5e6240}, {0x2b92038, 0xc00bd2d430}, 0xc000f0ad20, {0x2b99530, 0xc016c246d8}, 0x24fa8d?)
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]:         github.com/tendermint/tendermint@v0.34.21/state/execution.go:327 +0x54e
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]: github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc000dd9380, 0x26}}, {0xc00bd3e0c0, 0xe}, 0x1, 0x24fa8d, {{0xc00b910b00, ...}, ...}, ...}, ...)
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]:         github.com/tendermint/tendermint@v0.34.21/state/execution.go:140 +0x171
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]: github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlock(_, {{{0xb, 0x0}, {0xc000dd9380, 0x26}}, {0xc00bd3e0c0, 0xe}, 0x1, 0x24fa8d, {{0xc00b910b00, ...}, ...}, ...}, ...)
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]:         github.com/tendermint/tendermint@v0.34.21/consensus/replay.go:503 +0x23c
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]: github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0xc000dd9380, 0x26}}, {0xc00bd3e0c0, 0xe}, 0x1, 0x24fa8d, {{0xc00b910b00, ...}, ...}, ...}, ...)
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]:         github.com/tendermint/tendermint@v0.34.21/consensus/replay.go:416 +0x7ae
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]: github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc002c8d7b8, {0x2b9a9c0, 0xc000cfcb60})
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]:         github.com/tendermint/tendermint@v0.34.21/consensus/replay.go:268 +0x3c8
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]: github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0xc000dd9380, 0x26}}, {0xc00bd3e0c0, 0xe}, 0x1, 0x24fa8d, ...}, ...)
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]:         github.com/tendermint/tendermint@v0.34.21/node/node.go:330 +0x1b8
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]: github.com/tendermint/tendermint/node.NewNode(0xc00012a640, {0x2b869f0, 0xc001105cc0}, 0xc002c92600, {0x2b6e240, 0xc00845cfc0}, 0x0?, 0x0?, 0xc002c92790, {0x2b8b7c8, ...}, ...)
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]:         github.com/tendermint/tendermint@v0.34.21/node/node.go:778 +0x597
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]: github.com/evmos/ethermint/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x2ba2d80, 0xc001106bd0}, {0x0, 0x0}, {0x2b8f0e8, 0xc000df0ec0}, ...}, ...)
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]:         github.com/evmos/ethermint@v0.19.3/server/start.go:310 +0xcd3
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]: github.com/evmos/ethermint/server.StartCmd.func2(0xc0005aaa00?, {0xc0010ce9c0?, 0x0?, 0x4?})
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]:         github.com/evmos/ethermint@v0.19.3/server/start.go:119 +0x228
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]: github.com/spf13/cobra.(*Command).execute(0xc0005aaa00, {0xc0010ce980, 0x4, 0x4})
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]:         github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]: github.com/spf13/cobra.(*Command).ExecuteC(0xc001194c80)
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]:         github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]: github.com/spf13/cobra.(*Command).Execute(...)
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]:         github.com/spf13/cobra@v1.5.0/command.go:918
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]: github.com/spf13/cobra.(*Command).ExecuteContext(...)
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]:         github.com/spf13/cobra@v1.5.0/command.go:911
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]: github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x210f51d?, {0xc001305050, 0x10})
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]:         github.com/cosmos/cosmos-sdk@v0.45.9/server/cmd/execute.go:36 +0x1eb
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]: main.main()
Feb 06 23:11:55 HOSTNAME_REDACTED xplad[3027968]:         github.com/xpladev/xpla/cmd/xplad/main.go:26 +0x65
Feb 06 23:11:55 HOSTNAME_REDACTED systemd[1]: xpla.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 06 23:11:55 HOSTNAME_REDACTED systemd[1]: xpla.service: Failed with result 'exit-code'.
```

**Comment by caramis** [comment]
Governance voting for network upgrade (xplad v1.2.0) is in progress.
